import { APP_PREFIX_PATH } from '@/constants/route.constant'
import { NAV_ITEM_TYPE_TITLE, NAV_ITEM_TYPE_ITEM } from '@/constants/navigation.constant'
import {
    ALL_APP_ROLES,
    SUPERVISOR_AND_ADMIN,
} from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const mainNavigationConfig: NavigationTree[] = [
    {
        key: 'inicio',
        path: '',
        title: 'INICIO',
        translateKey: 'nav.inicio',
        icon: 'inicio',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ALL_APP_ROLES,
        subMenu: [
            {
                key: 'app.dashboard',
                path: `${APP_PREFIX_PATH}/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: SUPERVISOR_AND_ADMIN,
                subMenu: [],
            },
            {
                key: 'app.clientsAndWorks',
                path: `${APP_PREFIX_PATH}/clients-works`,
                title: 'Clientes y Obras',
                translateKey: 'nav.clientsAndWorks',
                icon: 'clientesObras',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ALL_APP_ROLES,
                subMenu: [],
            },
            {
                key: 'app.cotizaciones',
                path: `${APP_PREFIX_PATH}/cotizaciones`,
                title: 'Cotizaciones',
                translateKey: 'nav.cotizaciones',
                icon: 'cotizaciones',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ALL_APP_ROLES,
                subMenu: [],
            },
            {
                key: 'app.pedidos',
                path: `${APP_PREFIX_PATH}/pedidos`,
                title: 'Pedidos',
                translateKey: 'nav.pedidos',
                icon: 'pedidos',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ALL_APP_ROLES,
                subMenu: [],
            },
            {
                key: 'app.programacion',
                path: `${APP_PREFIX_PATH}/programacion`,
                title: 'Programación',
                translateKey: 'nav.programacion',
                icon: 'programacion',
                type: NAV_ITEM_TYPE_ITEM,
                authority: SUPERVISOR_AND_ADMIN,
                subMenu: [],
            },
            {
                key: 'app.despacho',
                path: `${APP_PREFIX_PATH}/despacho`,
                title: 'Despacho',
                translateKey: 'nav.despacho',
                icon: 'despacho',
                type: NAV_ITEM_TYPE_ITEM,
                authority: SUPERVISOR_AND_ADMIN,
                subMenu: [],
            },
            {
                key: 'app.trazabilidad',
                path: `${APP_PREFIX_PATH}/trazabilidad`,
                title: 'Trazabilidad',
                translateKey: 'nav.trazabilidad',
                icon: 'trazabilidad',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ALL_APP_ROLES,
                subMenu: [],
            },
            {
                key: 'app.facturacion',
                path: `${APP_PREFIX_PATH}/facturacion`,
                title: 'Facturación',
                translateKey: 'nav.facturacion',
                icon: 'facturacion',
                type: NAV_ITEM_TYPE_ITEM,
                authority: SUPERVISOR_AND_ADMIN,
                subMenu: [],
            },
            {
                key: 'app.cobranza',
                path: `${APP_PREFIX_PATH}/cobranza`,
                title: 'Cobranza',
                translateKey: 'nav.cobranza',
                icon: 'cobranza',
                type: NAV_ITEM_TYPE_ITEM,
                authority: SUPERVISOR_AND_ADMIN,
                subMenu: [],
            },
        ],
    },
    {
        key: 'configuracion',
        path: '',
        title: 'CONFIGURACIÓN',
        translateKey: 'nav.configuracion',
        icon: 'configuracion',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ALL_APP_ROLES,
        subMenu: [
            {
                key: 'app.usuarios',
                path: `${APP_PREFIX_PATH}/usuarios`,
                title: 'Usuarios',
                translateKey: 'nav.usuarios',
                icon: 'usuarios',
                type: NAV_ITEM_TYPE_ITEM,
                authority: SUPERVISOR_AND_ADMIN,
                subMenu: [],
            },
        ],
    },
]

export default mainNavigationConfig
